name: amantak2
description: نظام محلي لإدارة أفراد الأمن والحضور والعهد والجزاءات.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  image_picker: ^1.2.3
  path_provider: ^2.1.6
  sqflite: ^2.4.2+1
  path: ^1.9.1

  excel: ^4.0.6
  share_plus: ^9.0.0
  pdf: ^3.10.8
  printing: ^5.11.1
  
  # 🚨 المكتبات للاتصال بـ Firebase ورفع الصور 🚨
  firebase_core: ^2.30.0
  cloud_firestore: ^4.15.0
  firebase_storage: ^11.6.0
  
  # 🚨 مكتبة التحليل الذكي للصور (قراءة النصوص) 🚨
  google_mlkit_text_recognition: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  xml: ^7.0.1
  web: ^1.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/fonts/
